sudo: required
language: node_js
node_js:
- 4.4.4
before_install:
- npm install -g npm@3.8.9
- npm --version
compiler: clang-3.6
env:
  global:
  - CXX=clang-3.6
  - DOCKER_EMAIL=awong.dev@gmail.com
  - DOCKER_USERNAME=awongdev
  - secure: nyOcp09Xzs9RhOF7wqRGk5yJ8e+NVXGaJVr79LvzrknZAHKrB3QMptC/rECGKTKdrwHr7Jas6/+mK36ZpIVUEF1P3EdDrsCYd6Vrgk+NS4UlgEBzCz5qnxaeLp1RA4BZ2pUVXQyavlQnRGgODiqw4C9aI4VKyaiz4QaskDH9fra/Sz8afmkwoSl0jKXn0kl+DstMrP71rJHZ31eznLC6d2AW8Y/LcA+7Abi5yq9ltDwK9h6RUB4VlTNJiis6xPyegw8OmIKIMpsnfeQpbf2oYpodxp4zLtJlr5RdXXli2zQ67mibtt/0+1dqsNQpxIdT9NU9ZucM1bBuiCbTJfd+7IURJkhz+4AU+vzenH9RNvYu5zqS/ykIhQGSi4L2QPWHJ1u++D97seJQ5BMUl85ZejdmVVhauV0AwPvrBplnZGHw6k9fuc5PZWHQGDLKynt/Jo/kHePLvbxTPGpYa+eU/uCRzdmxtJU0UBQucaj+S3Ub0mwyFpfYyOmED03AhNvodZVmLnx9EKfOq1t33+cnRYpAvvmWH0X0xtNC/HTfaBAwsrapr9mwFaZV4zIHVWqo9o70/HEvTe1/PQ0iC/N1FeKRxJ34cxTs4hUVE027wJc07jqyMs5tbn4fj2cLJXav3jGoKnS/lR9FKVl2VMoNhxr+/lMmykXTiBQ84noroww=
  - secure: S8Wlf+8BaEK7/SWo6uymzfmcSMEwrwJRD1mxahnX89IS9xfRa4Udx7giXHVhDIENgluzFuzf7oE1klza/67XC6XjqFWu3rHscx26t1AO21Tphj6d1GbXKbSmlt2lefDXmFmGAHdXVFwtvFPRUFPRHH7edhBLXykwLR4CFp805fMaYS/uhWlibm4FHdyuUyZgzHIRq0ky2vmnMqEusgnzpRwVJRDbgdqBAKl6VDs2AujI9mR4SV2LyyQpqoTw6Lo/Nx7SQF8/cZ9sN3Gn0kr9WLZ2mtAg4x6LnwBnDl124FpjjCWoh6nOiQhtR0jWJsox8SpwLJCVwaZJdbeFu6AD7KUoXAbuGL4leyWHXBbIvXYMIpkd2qncGkw6nbIfredDqUEYlaZKeuanPif1VHWttM8E8V/ndYSzt64sEIQCFJXNO/dRsjZZ+qrly4Iv1D6JIInJOCh17eAzkTD9ZFYkXrLQxp9q8yqLoJuYymshsmiN8KChfob96M6ZKlul0gRAfOPxxZyIQoK4VJCe/ZH7WDdo1WPk0lQGOcll0dkZezNBO274gjdRyBVwCOHfBQjuboXB6oK1lbysbOx1xoKvO+qQbdFa7sL8WQ+44vd+hzErJ3fgcFJ6jrSljijEXU2WCu9MWG3d094HzOjrfz1NGfTPGbgk/dSjb5Y/6FS9gTU= # SAUCE_ACCESS_KEY
  - secure: MyA8/1PCYKSm2/es3x8NWEwXDChKitQT+5Hf+ShI4yrUDC/8sCNZUJn4Pg3/eQJgNcUMYtBjjgHvFPux9pSPhy7zHW3kqMm0aN6ow4SnHBQptix5F/C/5BcdEEJKXQwqx6nwMb0vQiONS/zsYOkawwfdMvhRBkubAVuX5+RWnDLxnFs31fhLI4VrR7aZYZU3Mp9uGWWYdLAgPwZE5xXpYpv5TaPj5KSAhJSzGGiUNuja4eUzZUpP6eNQD96MV7t/0q4ugHD9CAV49722j6oZu+iYm4haZVhbLAW6RsL6BVZ27WS07eLvo+8bOmS/qvLAxwbHkBjSFCNivwnaY8+cm4x1bWO6MCK+WVRKxmCcvxf3j/8vGH+6SxT3u6/b2oVArKdIqLiYKYmib0dfUuS1iSJZ/ww4NygV7q7CI/PgSv4mZhPseavrqH4jAKekMTXg7sS9KjuVnFBhchrwJZkAZlG2eaGikpPNEU/NySBNr8FowxZc3YAffPeyXDx5+2iQETf3hA18ZATK/pi1tUVdsSOINVz6VchWuDNF6sMUMq9ecW5y5m4NcSKSEE1Um/K49pAXdnVjjjhwm1Qm68AhX2OW/IYHYtzA47qZ92qe82Y8PzLDhFMXyheFg7l1TfNFYzWfkUxJz3lh8SWmb4x2pUqyjpuoJ9i7EMdUslNfGic= # SAUCE_USERNAME
services:
- docker
script:
  nightwatch --config test/e2e/nightwatch.js --env travis
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - g++-4.8
  sauce_connect:
    username: alexose
    access_key:
      secure: QtQxSF0wgv2ksYwf2+O4MM302xtfqBp/fycMJhm1Q5biA/ilezVJnFq1NZhM6bgX5C1wRFaeEQNy7MvhHRoPh9bN3/8NntPZA4QmsblYkTLE/pf4b8pnnqHE+tc174KFtTzvQ7sWZUTyur38GaE1/FgWUHY7fmVJxxbRigb8iHbq8bFw6G/lpfV8O4HEosvqMGUNERjWCTVB+/T3y6IXFJOZRM4+8WIAxD4NpYCJvKNFNEzc1rxbZu4yZuTZa4vAxHQ3P0F70qGD/4NF2jrV60JIjv7LD1f7mRzATkmLkVuIXEKREKmSUEIydbYBsxwkRFW4FsmGbv1b0GV/+t5pTUkirjlR36kWfJ/JFH1MDoQm3Dhc7AsGYYSvbUYLpLwXRBIxV1r2x20po9QWcaF0LFCwwVp3Dj5K14rSvfCRtgfIeryiOeH4FVTFDC+uKUf2X5Zsh12Pmo4ujB1plqRYZ71V0t5YTxLimoWvPLVJwSQnNWvhC8DmeAckIdle2T4mHIlP0SW78M7NnUBV4OnYTxwvAabB3MOloQd3fPobL4u0GIifE+wPsxiiHFCRaHoqb27GQYeRkQFUx20P0pSEPvh5ThciPD98Aqr1zn9hrhj8RDJtGOhpf7NPLpdUMPQtmwve9rnmsk/mcTd2FCLSdO7nmM1bCk/dwFsDx+U1o7k=
cache:
  apt: true
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: script
  script: "./scripts/release-docker.sh"
  skip_cleanup: true
  on:
    branch: master
